apiVersion: v1
kind: ConfigMap
metadata:
  name: kos-adapter-cm
  namespace: oteam-mvne-ns
data:
  SERVER_PORT: "8083"
  KOS_MOCK_BASE_URL: "http://kos-mock-svc"
  USE_REAL_KOS: "false"
  STAMP_ENABLED: "true"
  STAMP_HEADER_NAME: "X-MVNO-Stamp"
  STAMP_DEFAULT: "default-stamp"
  CIRCUIT_BREAKER_SLIDING_WINDOW_SIZE: "10"
  CIRCUIT_BREAKER_MINIMUM_CALLS: "5"
  CIRCUIT_BREAKER_FAILURE_RATE: "50"
  CIRCUIT_BREAKER_WAIT_DURATION: "30000"
  CIRCUIT_BREAKER_PERMITTED_CALLS_HALF_OPEN: "3"
