apiVersion: v1
kind: ConfigMap
metadata:
  name: kos-mock-cm
  namespace: oteam-mvne-ns
data:
  SERVER_PORT: "8084"
  BILLING_CHANGE_NOTIFICATION_URL: "http://billing-svc:8081/api/notifications/billing-change"
  NOTIFICATION_SCHEDULE_ENABLED: "true"
  NOTIFICATION_SCHEDULE_CRON: "0 0/5 * * * ?"
