# File: mp-server\kos-mock\src\main\resources\application.yml
server:
  port: ${SERVER_PORT:8084}
  servlet:
    context-path: /

spring:
  application:
    name: kos-mock-service
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:kosmockdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  main:
    allow-bean-definition-overriding: true
  security:
    user:
      name: ${SECURITY_USER:admin}
      password: ${SECURITY_PASSWORD:admin}

# 모의 데이터 생성 및 초기화 설정
mock:
  data:
    initialization:
      enabled: true
  notification:
    billing-change:
      enabled: ${NOTIFICATION_SCHEDULE_ENABLED:false}
      cron: ${NOTIFICATION_SCHEDULE_CRON:0 0/5 * * * ?}

# 로깅 설정
logging:
  level:
    com.ktds.mvne: ${LOG_LEVEL:DEBUG}
    org.springframework: INFO

# Swagger 설정
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  api-docs:
    path: /api-docs

# 실제 환경에서는 요청 대상 마이크로서비스 주소
billing-service:
  url: ${BILLING_SERVICE_URL:http://localhost:8081}