apiVersion: v1
kind: Service
metadata:
  name: kos-adapter-svc
  namespace: oteam-mvne-ns
spec:
  selector:
    app: kos-adapter
  ports:
  - port: 80
    targetPort: 8083
  type: ClusterIP
