apiVersion: v1
kind: Service
metadata:
  name: postgresql-billing-lb
  namespace: oteam-mvne-ns
spec:
  type: LoadBalancer
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: postgresql-billing

