apiVersion: v1
kind: Service
metadata:
  name: redis-master-lb
  namespace: oteam-mvne-ns
spec:
  type: LoadBalancer
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: redis
    app.kubernetes.io/component: master
