apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing
  namespace: oteam-mvne-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: billing
  template:
    metadata:
      labels:
        app: billing
    spec:
      containers:
      - name: billing
        image: oteamcr.azurecr.io/mvne/billing:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        resources:
          requests:
            cpu: 256m
            memory: 256Mi
          limits:
            cpu: 1024m
            memory: 1024Mi
        envFrom:
        - configMapRef:
            name: common-cm
        - configMapRef:
            name: billing-cm
        - secretRef:
            name: common-secret
        - secretRef:
            name: billing-secret
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
