apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  namespace: oteam-mvne-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: oteamcr.azurecr.io/mvne/product:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        resources:
          requests:
            cpu: 256m
            memory: 256Mi
          limits:
            cpu: 1024m
            memory: 1024Mi
        envFrom:
        - configMapRef:
            name: common-cm
        - configMapRef:
            name: product-cm
        - secretRef:
            name: common-secret
        - secretRef:
            name: product-secret
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
