server:
  port: ${SERVER_PORT:8081}
  servlet:
    context-path: /

spring:
  application:
    name: billing-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:billing_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    timeout: ${REDIS_TIMEOUT:2000}
  security:
    user:
      name: ${SECURITY_USER:admin}
      password: ${SECURITY_PASSWORD:admin}

# Azure Service Bus configuration
azure:
  servicebus:
    connection-string: ${AZURE_SERVICEBUS_CONNECTION_STRING:}
    topic:
      billing-change: ${AZURE_SERVICEBUS_TOPIC_BILLING_CHANGE:billing-change-topic}
    subscription:
      billing-change: ${AZURE_SERVICEBUS_SUBSCRIPTION_BILLING_CHANGE:billing-service-subscription}

# KOS Adapter service configuration
kos-adapter:
  base-url: ${KOS_ADAPTER_BASE_URL:http://localhost:8083}

# Cache configuration
cache:
  billing-info:
    ttl-hours: ${CACHE_BILLING_INFO_TTL_HOURS:24}

# Logging
logging:
  level:
    com.ktds.mvne: ${LOG_LEVEL:DEBUG}
    com.ktds.mvne.billing: ${LOG_LEVEL:DEBUG}
    org.springframework: INFO

# Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  api-docs:
    path: /api-docs

# add  Actuator
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - metrics
          - prometheus
  metrics:
    export:
      prometheus:
        enabled: true